version: "3"
services:
  spring:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/happireshipi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - mynet
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://spring:8080/" ]
      interval: 10s
      timeout: 10s
      retries: 3
  frontend:
    build:
      context: ./../happireshipi_front/
    ports:
      - "8081:8081"
    depends_on:
      - spring
    links:
      - spring
    networks:
      - mynet
    restart: on-failure
  db:
    image: "postgres:15.1-bullseye"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=happireshipi
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
