version: "3"
services:
  spring:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ./../happireshipi_front/
    ports:
      - "8081:8081"
    depends_on:
      - spring
  db:
    image: "postgres:15.1-bullseye"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
